linters-settings:
  maligned:
    suggest-new: true
  lll:
    line-length: 140

issues:
  exclude-use-default: false

linters:
  enable-all: true
  disable:
    - dupl
    - funlen
    - gochecknoglobals
    - gocognit
    - gomnd
    - gosec
    - scopelint
    - wsl
