// Code generated by awsgen from api version 2015-03-31. DO NOT EDIT.

package lambda

// Alias manages AWS Lambda Aliases.
type Alias struct {
	// A description of the alias.
	Description *string `cloudformation:"Description" input:"description"`

	// The name of the Lambda function.
	//
	// Name formats
	//
	//   Function name - MyFunction.
	//   Function ARN - arn:aws:lambda:us-west-2:123456789012:function:MyFunction.
	//   Partial ARN - 123456789012:function:MyFunction.
	//
	// The length constraint applies only to the full ARN. If you specify only the
	// function name, it is limited to 64 characters in length.
	FunctionName string `cloudformation:"FunctionName" input:"function_name"`

	// The function version that the alias invokes.
	FunctionVersion string `cloudformation:"FunctionVersion" input:"function_version"`

	// The name of the alias.
	Name string `cloudformation:"Name" input:"name"`

	// The routing configuration of the alias.
	RoutingConfig *struct {
		// The name of the second alias, and the percentage of traffic that's
		// routed to it.
		AdditionalVersionWeights map[string]string `cloudformation:"AdditionalVersionWeights" input:"additional_version_weights"`
	} `cloudformation:"RoutingConfig" input:"routing_config"`

	// Outputs:

	// The Amazon Resource Name (ARN) of the alias.
	ARN *string `json:"AliasArn" output:"arn"`

	// A unique identifier that changes when you update the alias.
	RevisionID *string `json:"RevisionId" output:"revision_id"`
}

// CloudFormationType returns the CloudFormation type for a AWS Lambda Alias.
func (Alias) CloudFormationType() string { return "AWS::Lambda::Alias" }
