// Code generated by awsgen from api version 2015-03-31. DO NOT EDIT.

package lambda

// LayerVersionPermission manages AWS Lambda LayerVersionPermissions.
type LayerVersionPermission struct {
	// The API action that grants access to the layer. For example,
	// lambda:GetLayerVersion.
	Action string `cloudformation:"Action" input:"action"`

	// The name or Amazon Resource Name (ARN) of the layer.
	LayerName string `input:"layer_name"`

	// With the principal set to *, grant permission to all accounts in the
	// specified organization.
	OrganizationID *string `cloudformation:"OrganizationId" input:"organization_id" json:"OrganizationId"`

	// An account ID, or * to grant permission to all AWS accounts.
	Principal string `cloudformation:"Principal" input:"principal"`

	// Only update the policy if the revision ID matches the ID specified. Use
	// this option to avoid modifying a policy that has changed since you last
	// read it.
	RevisionID *string `input:"revision_id" json:"RevisionId"`

	// An identifier that distinguishes the policy from others on the same
	// layer version.
	StatementID string `input:"statement_id" json:"StatementId"`

	// The version number.
	VersionNumber int `input:"version_number"`

	// Outputs:

	// The permission statement.
	Statement *string `output:"statement"`
}

// CloudFormationType returns the CloudFormation type for a AWS Lambda LayerVersionPermission.
func (LayerVersionPermission) CloudFormationType() string {
	return "AWS::Lambda::LayerVersionPermission"
}
