// Code generated by "stringer -type StackOperation -trimprefix Stack"; DO NOT EDIT.

package cloudformation

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StackCreate-0]
	_ = x[StackUpdate-1]
	_ = x[StackDelete-2]
	_ = x[StackImport-3]
	_ = x[StackCleanup-4]
	_ = x[StackReview-5]
	_ = x[StackRollback-6]
}

const _StackOperation_name = "CreateUpdateDeleteImportCleanupReviewRollback"

var _StackOperation_index = [...]uint8{0, 6, 12, 18, 24, 31, 37, 45}

func (i StackOperation) String() string {
	if i < 0 || i >= StackOperation(len(_StackOperation_index)-1) {
		return "StackOperation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StackOperation_name[_StackOperation_index[i]:_StackOperation_index[i+1]]
}
