// Code generated by "stringer -type State -trimprefix State"; DO NOT EDIT.

package cloudformation

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateInProgress-0]
	_ = x[StateFailed-1]
	_ = x[StateComplete-2]
	_ = x[StateSkipped-3]
}

const _State_name = "InProgressFailedCompleteSkipped"

var _State_index = [...]uint8{0, 10, 16, 24, 31}

func (i State) String() string {
	if i < 0 || i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
