// Code generated by awsgen from api version 2010-05-08. DO NOT EDIT.

package iam

import "time"

// Group manages AWS Identity and Access Management Groups.
type Group struct {
	// The name of the group to create. Do not include the path in this
	// value.IAM user, group, role, and policy names must be unique within the
	// account. Names are not distinguished by case. For example, you cannot
	// create resources named both "MyResource" and "myresource".
	Name string `cloudformation:"GroupName" input:"name" json:"GroupName"`

	//  The path to the group. For more information about paths, see IAM
	// Identifiers:
	// https://docs.aws.amazon.com/IAM/latest/UserGuide/Using_Identifiers.html
	// in the IAM User Guide.This parameter is optional. If it is not included,
	// it defaults to a slash (/).This parameter allows (through its regex
	// pattern) a string of characters consisting of either a forward slash (/)
	// by itself or a string that must begin and end with forward slashes. In
	// addition, it can contain any ASCII character from the ! (\u0021) through
	// the DEL character (\u007F), including most punctuation characters,
	// digits, and upper and lowercased letters.
	Path *string `cloudformation:"Path" input:"path"`

	// Outputs:

	//  The Amazon Resource Name (ARN) specifying the group. For more
	// information about ARNs and how to use them in policies, see IAM
	// Identifiers:
	// https://docs.aws.amazon.com/IAM/latest/UserGuide/Using_Identifiers.html
	// in the IAM User Guide.
	ARN string `cloudformation:"Arn,att" json:"Arn" output:"arn"`

	// The date and time, in ISO 8601 date-time format, when the group was
	// created.
	Created time.Time `json:"CreateDate" output:"created"`

	//  The stable and unique string identifying the group. For more
	// information about IDs, see IAM Identifiers:
	// https://docs.aws.amazon.com/IAM/latest/UserGuide/Using_Identifiers.html
	// in the IAM User Guide.
	ID string `json:"GroupId" output:"id"`
}

// CloudFormationType returns the CloudFormation type for a AWS Identity and Access Management Group.
func (Group) CloudFormationType() string { return "AWS::IAM::Group" }
