// Code generated by awsgen from api version 2010-05-08. DO NOT EDIT.

package iam

import "time"

// LoginProfile manages AWS Identity and Access Management LoginProfiles.
type LoginProfile struct {
	// The new password for the user.The regex pattern that is used to validate
	// this parameter is a string of characters. That string can include almost
	// any printable ASCII character from the space (\u0020) through the end of
	// the ASCII character range (\u00FF). You can also include the tab
	// (\u0009), line feed (\u000A), and carriage return (\u000D) characters.
	// Any of these characters are valid in a password. However, many tools,
	// such as the AWS Management Console, might restrict the ability to type
	// certain characters because they have special meaning within that tool.
	Password string `input:"password"`

	// Specifies whether the user is required to set a new password on next
	// sign-in.
	PasswordResetRequired *bool `input:"password_reset_required"`

	// The name of the IAM user to create a password for. The user must already
	// exist.This parameter allows (through its regex pattern) a string of
	// characters consisting of upper and lowercase alphanumeric characters
	// with no spaces. You can also include any of the following characters:
	// _+=,.@-
	UserName string `input:"user_name"`

	// Outputs:

	// A structure containing the user name and password create date.
	LoginProfile struct {
		// The date when the password for the user was created.
		CreateDate time.Time `output:"create_date"`

		// Specifies whether the user is required to set a new password on next
		// sign-in.
		PasswordResetRequired *bool `output:"password_reset_required"`

		// The name of the user, which can be used for signing in to the AWS
		// Management Console.
		UserName string `output:"user_name"`
	} `output:"login_profile"`
}
