// Code generated by awsgen from api version 2010-05-08. DO NOT EDIT.

package iam

import "time"

// Role manages AWS Identity and Access Management Roles.
type Role struct {
	// The trust relationship policy document that grants an entity permission to assume the role.In IAM,
	// you must provide a JSON policy that has been converted to a string. However, for AWS CloudFormation
	// templates formatted in YAML, you can provide the policy in JSON or YAML format. AWS CloudFormation
	// always converts a YAML policy to JSON format before submitting it to IAM.The regex pattern used to
	// validate this parameter is a string of characters consisting of the following:  Any printable ASCII
	// character ranging from the space character (\u0020) through the end of the ASCII character range
	//   The printable characters in the Basic Latin and Latin-1 Supplement character set (through \u00FF)
	//   The special characters tab (\u0009), line feed (\u000A), and carriage return (\u000D)
	//
	//  Upon success, the response includes the same trust policy in JSON format.
	AssumeRolePolicy string `cloudformation:"AssumeRolePolicyDocument" input:"assume_role_policy" json:"AssumeRolePolicyDocument"`

	// A description of the role.
	Description *string `cloudformation:"Description" input:"description"`

	// The maximum session duration (in seconds) that you want to set for the
	// specified role. If you do not specify a value for this setting, the
	// default maximum of one hour is applied. This setting can have a value
	// from 1 hour to 12 hours.Anyone who assumes the role from the AWS CLI or
	// API can use the DurationSeconds API parameter or the duration-seconds
	// CLI parameter to request a longer session. The MaxSessionDuration
	// setting determines the maximum duration that can be requested using the
	// DurationSeconds parameter. If users don't specify a value for the
	// DurationSeconds parameter, their security credentials are valid for one
	// hour by default. This applies when you use the AssumeRole* API
	// operations or the assume-role* CLI operations but does not apply when
	// you use those operations to create a console URL. For more information,
	// see Using IAM Roles:
	// https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html in
	// the IAM User Guide.
	MaxSessionDuration *int `cloudformation:"MaxSessionDuration" input:"max_session_duration"`

	//  The path to the role. For more information about paths, see IAM
	// Identifiers:
	// https://docs.aws.amazon.com/IAM/latest/UserGuide/Using_Identifiers.html
	// in the IAM User Guide.This parameter is optional. If it is not included,
	// it defaults to a slash (/).This parameter allows (through its regex
	// pattern) a string of characters consisting of either a forward slash (/)
	// by itself or a string that must begin and end with forward slashes. In
	// addition, it can contain any ASCII character from the ! (\u0021) through
	// the DEL character (\u007F), including most punctuation characters,
	// digits, and upper and lowercased letters.
	Path *string `cloudformation:"Path" input:"path"`

	// The ARN of the policy that is used to set the permissions boundary for
	// the role.
	PermissionsBoundary *string `cloudformation:"PermissionsBoundary" input:"permissions_boundary"`

	// The name of the role to create.IAM user, group, role, and policy names
	// must be unique within the account. Names are not distinguished by case.
	// For example, you cannot create resources named both "MyResource" and
	// "myresource".
	Name string `cloudformation:"RoleName" input:"name" json:"RoleName"`

	// A list of tags that you want to attach to the newly created role. Each
	// tag consists of a key name and an associated value. For more information
	// about tagging, see Tagging IAM Identities:
	// https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html in the IAM
	// User Guide.If any one of the tags is invalid or if you exceed the
	// allowed number of tags per role, then the entire request fails and the
	// role is not created.
	Tags []struct {
		// The key name that can be used to look up or retrieve the associated
		// value. For example, Department or Cost Center are common choices.
		Key string `input:"key"`

		// The value associated with this tag. For example, tags with a key name of
		// Department could have values such as Human Resources, Accounting, and
		// Support. Tags with a key name of Cost Center might have values that
		// consist of the number associated with the different cost centers in your
		// company. Typically, many resources have tags with the same key name but
		// with different values.AWS always interprets the tag Value as a single
		// string. If you need to store an array, you can store comma-separated
		// values in the string. However, you must interpret the value in your
		// code.
		Value string `input:"value"`
	} `cloudformation:"Tags" input:"tags"`

	// Outputs:

	//  The Amazon Resource Name (ARN) specifying the role. For more
	// information about ARNs and how to use them in policies, see IAM
	// Identifiers:
	// https://docs.aws.amazon.com/IAM/latest/UserGuide/Using_Identifiers.html
	// in the IAM User Guide guide.
	ARN string `cloudformation:"Arn,att" json:"Arn" output:"arn"`

	// The date and time, in ISO 8601 date-time format, when the role was
	// created.
	CreateDate time.Time `output:"create_date"`

	//  The stable and unique string identifying the role. For more information
	// about IDs, see IAM Identifiers:
	// https://docs.aws.amazon.com/IAM/latest/UserGuide/Using_Identifiers.html
	// in the IAM User Guide.
	RoleID string `cloudformation:"RoleId,att" json:"RoleId" output:"role_id"`

	// Contains information about the last time that an IAM role was used. This
	// includes the date and time and the Region in which the role was last
	// used. Activity is only reported for the trailing 400 days. This period
	// can be shorter if your Region began supporting these features within the
	// last year. The role might have been used more than 400 days ago. For
	// more information, see Regions Where Data Is Tracked:
	// https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_access-advisor.html#access-advisor_tracking-period
	// in the IAM User Guide.
	RoleLastUsed *struct {
		// The date and time, in ISO 8601 date-time format that the role was last
		// used.This field is null if the role has not been used within the IAM
		// tracking period. For more information about the tracking period, see
		// Regions Where Data Is Tracked:
		// https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_access-advisor.html#access-advisor_tracking-period
		// in the IAM User Guide.
		LastUsedDate *time.Time `output:"last_used_date"`

		// The name of the AWS Region in which the role was last used.
		Region *string `output:"region"`
	} `output:"role_last_used"`
}

// CloudFormationType returns the CloudFormation type for a AWS Identity and Access Management Role.
func (Role) CloudFormationType() string { return "AWS::IAM::Role" }
