// Code generated by awsgen from api version 2010-05-08. DO NOT EDIT.

package iam

// SAMLProvider manages AWS Identity and Access Management SAMLProviders.
type SAMLProvider struct {
	// The name of the provider to create.This parameter allows (through its
	// regex pattern) a string of characters consisting of upper and lowercase
	// alphanumeric characters with no spaces. You can also include any of the
	// following characters: _+=,.@-
	Name string `input:"name"`

	// An XML document generated by an identity provider (IdP) that supports
	// SAML 2.0. The document includes the issuer's name, expiration
	// information, and keys that can be used to validate the SAML
	// authentication response (assertions) that are received from the IdP. You
	// must generate the metadata document using the identity management
	// software that is used as your organization's IdP.For more information,
	// see About SAML 2.0-based Federation:
	// https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_saml.html
	// in the IAM User Guide
	SAMLMetadataDocument string `input:"saml_metadata_document"`

	// Outputs:

	// The Amazon Resource Name (ARN) of the new SAML provider resource in IAM.
	SAMLProviderARN *string `json:"SAMLProviderArn" output:"saml_provider_arn"`
}
