// Code generated by awsgen from api version 2010-05-08. DO NOT EDIT.

package iam

import "time"

// ServiceSpecificCredential manages AWS Identity and Access Management
// ServiceSpecificCredentials.
type ServiceSpecificCredential struct {
	// The name of the AWS service that is to be associated with the
	// credentials. The service you specify here is the only service that can
	// be accessed using these credentials.
	ServiceName string `input:"service_name"`

	// The name of the IAM user that is to be associated with the credentials.
	// The new service-specific credentials have the same permissions as the
	// associated user except that they can be used only to access the
	// specified service.This parameter allows (through its regex pattern) a
	// string of characters consisting of upper and lowercase alphanumeric
	// characters with no spaces. You can also include any of the following
	// characters: _+=,.@-
	UserName string `input:"user_name"`

	// Outputs:

	// A structure that contains information about the newly created
	// service-specific credential.This is the only time that the password for
	// this credential set is available. It cannot be recovered later. Instead,
	// you must reset the password with ResetServiceSpecificCredential.
	ServiceSpecificCredential *struct {
		// The date and time, in ISO 8601 date-time format, when the
		// service-specific credential were created.
		CreateDate time.Time `output:"create_date"`

		// The name of the service associated with the service-specific credential.
		ServiceName string `output:"service_name"`

		// The generated password for the service-specific credential.
		ServicePassword string `output:"service_password"`

		// The unique identifier for the service-specific credential.
		ServiceSpecificCredentialID string `json:"ServiceSpecificCredentialId" output:"service_specific_credential_id"`

		// The generated user name for the service-specific credential. This value
		// is generated by combining the IAM user's name combined with the ID
		// number of the AWS account, as in jane-at-123456789012, for example. This
		// value cannot be configured by the user.
		ServiceUserName string `output:"service_user_name"`

		// The status of the service-specific credential. Active means that the key
		// is valid for API calls, while Inactive means it is not.
		Status string `output:"status"`

		// The name of the IAM user associated with the service-specific
		// credential.
		UserName string `output:"user_name"`
	} `output:"service_specific_credential"`
}
