// Code generated by awsgen from api version 2018-11-29. DO NOT EDIT.

package apigatewayv2

import "time"

// Api manages AmazonApiGatewayV2 Apis.
type Api struct {
	// An API key selection expression. Supported only for WebSocket APIs. See
	// API Key Selection Expressions.
	KeySelection *string `cloudformation:"ApiKeySelectionExpression" input:"key_selection" json:"ApiKeySelectionExpression"`

	// A CORS configuration. Supported only for HTTP APIs. See Configuring CORS
	// for more information.
	CORS *struct {
		// Specifies whether credentials are included in the CORS request.
		// Supported only for HTTP APIs.
		AllowCredentials *bool `cloudformation:"AllowCredentials" input:"allow_credentials"`

		// Represents a collection of allowed headers. Supported only for HTTP
		// APIs.
		AllowHeaders []string `cloudformation:"AllowHeaders" input:"allow_headers"`

		// Represents a collection of allowed HTTP methods. Supported only for HTTP
		// APIs.
		AllowMethods []string `cloudformation:"AllowMethods" input:"allow_methods"`

		// Represents a collection of allowed origins. Supported only for HTTP
		// APIs.
		AllowOrigins []string `cloudformation:"AllowOrigins" input:"allow_origins"`

		// Represents a collection of exposed headers. Supported only for HTTP
		// APIs.
		ExposeHeaders []string `cloudformation:"ExposeHeaders" input:"expose_headers"`

		// The number of seconds that the browser should cache preflight request
		// results. Supported only for HTTP APIs.
		MaxAge *int `cloudformation:"MaxAge" input:"max_age"`
	} `cloudformation:"CorsConfiguration" input:"cors" json:"CorsConfiguration"`

	// This property is part of quick create. It specifies the credentials
	// required for the integration, if any. For a Lambda integration, three
	// options are available. To specify an IAM Role for API Gateway to assume,
	// use the role's Amazon Resource Name (ARN). To require that the caller's
	// identity be passed through from the request, specify
	// arn:aws:iam::*:user/*. To use resource-based permissions on supported
	// AWS services, specify null. Currently, this property is not used for
	// HTTP integrations. Supported only for HTTP APIs.
	CredentialsARN *string `cloudformation:"CredentialsArn" input:"credentials_arn" json:"CredentialsArn"`

	// The description of the API.
	Description *string `cloudformation:"Description" input:"description"`

	// Avoid validating models when creating a deployment. Supported only for
	// WebSocket APIs.
	DisableSchemaValidation *bool `cloudformation:"DisableSchemaValidation" input:"disable_schema_validation"`

	// The name of the API.
	Name string `cloudformation:"Name" input:"name"`

	// The API protocol.
	Protocol string `cloudformation:"ProtocolType" input:"protocol" json:"ProtocolType"`

	// This property is part of quick create. If you don't specify a routeKey,
	// a default route of $default is created. The $default route acts as a
	// catch-all for any request made to your API, for a particular stage. The
	// $default route key can't be modified. You can add routes after creating
	// the API, and you can update the route keys of additional routes.
	// Supported only for HTTP APIs.
	RouteKey *string `cloudformation:"RouteKey" input:"route_key"`

	// The route selection expression for the API. For HTTP APIs, the
	// routeSelectionExpression must be ${request.method} ${request.path}. If
	// not provided, this will be the default for HTTP APIs. This property is
	// required for WebSocket APIs.
	RouteSelectionExpression *string `cloudformation:"RouteSelectionExpression" input:"route_selection_expression"`

	// The collection of tags. Each tag element is associated with a given
	// resource.
	Tags map[string]string `cloudformation:"Tags" input:"tags"`

	// This property is part of quick create. Quick create produces an API with
	// an integration, a default catch-all route, and a default stage which is
	// configured to automatically deploy changes. For HTTP integrations,
	// specify a fully qualified URL. For Lambda integrations, specify a
	// function ARN. The type of the integration will be HTTP_PROXY or
	// AWS_PROXY, respectively. Supported only for HTTP APIs.
	Target *string `cloudformation:"Target" input:"target"`

	// A version identifier for the API.
	Version *string `cloudformation:"Version" input:"version"`

	// Outputs:

	// The URI of the API, of the form
	// {api-id}.execute-api.{region}.amazonaws.com. The stage name is typically
	// appended to this URI to form a complete path to a deployed API stage.
	Endpoint *string `json:"ApiEndpoint" output:"endpoint"`

	// The API ID.
	ID *string `cloudformation:"Id,ref" json:"ApiId" output:"id"`

	// The timestamp when the API was created.
	Created *time.Time `json:"CreatedDate" output:"created"`

	// The validation information during API import. This may include
	// particular properties of your OpenAPI definition which are ignored
	// during import. Supported only for HTTP APIs.
	ImportInfo []string `output:"import_info"`

	// The warning messages reported when failonwarnings is turned on during
	// API import.
	Warnings []string `output:"warnings"`
}

// CloudFormationType returns the CloudFormation type for a AmazonApiGatewayV2 Api.
func (Api) CloudFormationType() string { return "AWS::ApiGatewayV2::Api" }
