// Code generated by awsgen from api version 2018-11-29. DO NOT EDIT.

package apigatewayv2

import "time"

// Deployment manages AmazonApiGatewayV2 Deployments.
type Deployment struct {
	// The API identifier.
	API string `cloudformation:"ApiId" input:"api" json:"ApiId"`

	// The description for the deployment resource.
	Description *string `cloudformation:"Description" input:"description"`

	// The name of the Stage resource for the Deployment resource to create.
	StageName *string `cloudformation:"StageName" input:"stage_name"`

	// Outputs:

	// Specifies whether a deployment was automatically released.
	AutoDeployed *bool `output:"auto_deployed"`

	// The date and time when the Deployment resource was created.
	Created *time.Time `json:"CreatedDate" output:"created"`

	// The identifier for the deployment.
	ID *string `json:"DeploymentId" output:"id"`

	// The status of the deployment: PENDING, FAILED, or SUCCEEDED.
	Status *string `json:"DeploymentStatus" output:"status"`

	// May contain additional feedback on the status of an API deployment.
	StatusMessage *string `json:"DeploymentStatusMessage" output:"status_message"`
}

// CloudFormationType returns the CloudFormation type for a AmazonApiGatewayV2 Deployment.
func (Deployment) CloudFormationType() string { return "AWS::ApiGatewayV2::Deployment" }
