// Code generated by awsgen from api version 2018-11-29. DO NOT EDIT.

package apigatewayv2

// Model manages AmazonApiGatewayV2 Models.
type Model struct {
	// The API identifier.
	API string `cloudformation:"ApiId" input:"api" json:"ApiId"`

	// The content-type for the model, for example, "application/json".
	ContentType *string `cloudformation:"ContentType" input:"content_type"`

	// The description of the model.
	Description *string `cloudformation:"Description" input:"description"`

	// The name of the model. Must be alphanumeric.
	Name string `cloudformation:"Name" input:"name"`

	// The schema for the model. For application/json models, this should be
	// JSON schema draft 4 model.
	Schema string `cloudformation:"Schema" input:"schema"`

	// Outputs:

	// The model identifier.
	ID *string `json:"ModelId" output:"id"`
}

// CloudFormationType returns the CloudFormation type for a AmazonApiGatewayV2 Model.
func (Model) CloudFormationType() string { return "AWS::ApiGatewayV2::Model" }
