// Code generated by awsgen from api. DO NOT EDIT.

package apigatewayv2

import "reflect"

// Registry maintains a list of supported apigatewayv2 resources.
type Registry interface {
	Add(typename string, typ reflect.Type)
}

// Register registers all AmazonApiGatewayV2 resources.
func Register(reg Registry) {
	reg.Add("aws:apigatewayv2_api", reflect.TypeOf(&Api{}))
	reg.Add("aws:apigatewayv2_api_mapping", reflect.TypeOf(&ApiMapping{}))
	reg.Add("aws:apigatewayv2_authorizer", reflect.TypeOf(&Authorizer{}))
	reg.Add("aws:apigatewayv2_deployment", reflect.TypeOf(&Deployment{}))
	reg.Add("aws:apigatewayv2_domain_name", reflect.TypeOf(&DomainName{}))
	reg.Add("aws:apigatewayv2_integration", reflect.TypeOf(&Integration{}))
	reg.Add("aws:apigatewayv2_integration_response", reflect.TypeOf(&IntegrationResponse{}))
	reg.Add("aws:apigatewayv2_model", reflect.TypeOf(&Model{}))
	reg.Add("aws:apigatewayv2_route", reflect.TypeOf(&Route{}))
	reg.Add("aws:apigatewayv2_route_response", reflect.TypeOf(&RouteResponse{}))
	reg.Add("aws:apigatewayv2_stage", reflect.TypeOf(&Stage{}))
	reg.Add("aws:apigatewayv2_vpc_link", reflect.TypeOf(&VpcLink{}))
}
