// Code generated by awsgen from api version 2018-11-29. DO NOT EDIT.

package apigatewayv2

// Route manages AmazonApiGatewayV2 Routes.
type Route struct {
	// The API identifier.
	API string `cloudformation:"ApiId" input:"api" json:"ApiId"`

	// Specifies whether an API key is required for the route. Supported only
	// for WebSocket APIs.
	APIKeyRequired *bool `cloudformation:"ApiKeyRequired" input:"api_key_required" json:"ApiKeyRequired"`

	// The authorization scopes supported by this route.
	AuthorizationScopes []string `cloudformation:"AuthorizationScopes" input:"authorization_scopes"`

	// The authorization type for the route. For WebSocket APIs, valid values
	// are NONE for open access, AWS_IAM for using AWS IAM permissions, and
	// CUSTOM for using a Lambda authorizer For HTTP APIs, valid values are
	// NONE for open access, or JWT for using JSON Web Tokens.
	AuthorizationType *string `cloudformation:"AuthorizationType" input:"authorization_type"`

	// The identifier of the Authorizer resource to be associated with this
	// route. The authorizer identifier is generated by API Gateway when you
	// created the authorizer.
	Authorizer *string `cloudformation:"AuthorizerId" input:"authorizer" json:"AuthorizerId"`

	// The model selection expression for the route. Supported only for
	// WebSocket APIs.
	ModelSelection *string `cloudformation:"ModelSelectionExpression" input:"model_selection" json:"ModelSelectionExpression"`

	// The operation name for the route.
	OperationName *string `cloudformation:"OperationName" input:"operation_name"`

	// The request models for the route. Supported only for WebSocket APIs.
	RequestModels map[string]string `cloudformation:"RequestModels" input:"request_models"`

	// The request parameters for the route. Supported only for WebSocket APIs.
	RequestParameters map[string]string `cloudformation:"RequestParameters" input:"request_parameters"`

	// The route key for the route.
	Key string `cloudformation:"RouteKey" input:"key" json:"RouteKey"`

	// The route response selection expression for the route. Supported only
	// for WebSocket APIs.
	RouteResponseSelectionExpression *string `cloudformation:"RouteResponseSelectionExpression" input:"route_response_selection_expression"`

	// The target for the route.
	Target *string `cloudformation:"Target" input:"target"`

	// Outputs:

	// Specifies whether a route is managed by API Gateway. If you created an
	// API using quick create, the $default route is managed by API Gateway.
	// You can't modify the $default route key.
	APIGatewayManaged *bool `json:"ApiGatewayManaged" output:"api_gateway_managed"`

	// The route ID.
	ID *string `json:"RouteId" output:"id"`
}

// CloudFormationType returns the CloudFormation type for a AmazonApiGatewayV2 Route.
func (Route) CloudFormationType() string { return "AWS::ApiGatewayV2::Route" }
