// Code generated by awsgen from api version 2018-11-29. DO NOT EDIT.

package apigatewayv2

// RouteResponse manages AmazonApiGatewayV2 RouteResponses.
type RouteResponse struct {
	// The API identifier.
	API string `cloudformation:"ApiId" input:"api" json:"ApiId"`

	// The model selection expression for the route response. Supported only
	// for WebSocket APIs.
	ModelSelectionExpression *string `cloudformation:"ModelSelectionExpression" input:"model_selection_expression"`

	// The response models for the route response.
	ResponseModels map[string]string `cloudformation:"ResponseModels" input:"response_models"`

	// The route response parameters.
	ResponseParameters map[string]string `cloudformation:"ResponseParameters" input:"response_parameters"`

	// The route ID.
	Route string `cloudformation:"RouteId" input:"route" json:"RouteId"`

	// The route response key.
	Key string `cloudformation:"RouteResponseKey" input:"key" json:"RouteResponseKey"`

	// Outputs:

	// Represents the identifier of a route response.
	ID *string `json:"RouteResponseId" output:"id"`
}

// CloudFormationType returns the CloudFormation type for a AmazonApiGatewayV2 RouteResponse.
func (RouteResponse) CloudFormationType() string { return "AWS::ApiGatewayV2::RouteResponse" }
