// Code generated by awsgen from api version 2018-11-29. DO NOT EDIT.

package apigatewayv2

import "time"

// Stage manages AmazonApiGatewayV2 Stages.
type Stage struct {
	// Settings for logging access in this stage.
	AccessLog *struct {
		// The ARN of the CloudWatch Logs log group to receive access logs.
		DestinationARN *string `cloudformation:"DestinationArn" input:"destination_arn" json:"DestinationArn"`

		// A single line format of the access logs of data, as specified by
		// selected $context variables. The format must include at least
		// $context.requestId.
		Format *string `cloudformation:"Format" input:"format"`
	} `cloudformation:"AccessLogSettings" input:"access_log" json:"AccessLogSettings"`

	// The API identifier.
	API string `cloudformation:"ApiId" input:"api" json:"ApiId"`

	// Specifies whether updates to an API automatically trigger a new
	// deployment. The default value is false.
	AutoDeploy *bool `cloudformation:"AutoDeploy" input:"auto_deploy"`

	// The identifier of a client certificate for a Stage. Supported only for
	// WebSocket APIs.
	ClientCertificateID *string `cloudformation:"ClientCertificateId" input:"client_certificate_id" json:"ClientCertificateId"`

	// The default route settings for the stage.
	DefaultRoute *struct {
		// Specifies whether (true) or not (false) data trace logging is enabled
		// for this route. This property affects the log entries pushed to Amazon
		// CloudWatch Logs. Supported only for WebSocket APIs.
		Tracing *bool `cloudformation:"DataTraceEnabled" input:"tracing" json:"DataTraceEnabled"`

		// Specifies whether detailed metrics are enabled.
		Metrics *bool `cloudformation:"DetailedMetricsEnabled" input:"metrics" json:"DetailedMetricsEnabled"`

		// Specifies the logging level for this route: INFO, ERROR, or OFF. This
		// property affects the log entries pushed to Amazon CloudWatch Logs.
		// Supported only for WebSocket APIs.
		LogLevel *string `cloudformation:"LoggingLevel" input:"log_level" json:"LoggingLevel"`

		// Specifies the throttling burst limit.
		ThrottlingBurstLimit *int `cloudformation:"ThrottlingBurstLimit" input:"throttling_burst_limit"`

		// Specifies the throttling rate limit.
		ThrottlingRateLimit *float64 `cloudformation:"ThrottlingRateLimit" input:"throttling_rate_limit"`
	} `cloudformation:"DefaultRouteSettings" input:"default_route" json:"DefaultRouteSettings"`

	// The deployment identifier of the API stage.
	Deployment *string `cloudformation:"DeploymentId" input:"deployment" json:"DeploymentId"`

	// The description for the API stage.
	Description *string `cloudformation:"Description" input:"description"`

	// Route settings for the stage, by routeKey.
	RouteSettings map[string]string `cloudformation:"RouteSettings" input:"route_settings"`

	// The name of the stage.
	Name string `cloudformation:"StageName" input:"name" json:"StageName"`

	// A map that defines the stage variables for a Stage. Variable names can
	// have alphanumeric and underscore characters, and the values must match
	// [A-Za-z0-9-._~:/?#&=,]+.
	Variables map[string]string `cloudformation:"StageVariables" input:"variables" json:"StageVariables"`

	// The collection of tags. Each tag element is associated with a given
	// resource.
	Tags map[string]string `cloudformation:"Tags" input:"tags"`

	// Outputs:

	// Specifies whether a stage is managed by API Gateway. If you created an
	// API using quick create, the $default stage is managed by API Gateway.
	// You can't modify the $default stage.
	APIGatewayManaged *bool `json:"ApiGatewayManaged" output:"api_gateway_managed"`

	// The timestamp when the stage was created.
	Created *time.Time `json:"CreatedDate" output:"created"`

	// Describes the status of the last deployment of a stage. Supported only
	// for stages with autoDeploy enabled.
	LastDeploymentStatusMessage *string `output:"last_deployment_status_message"`

	// The timestamp when the stage was last updated.
	Updated *time.Time `json:"LastUpdatedDate" output:"updated"`
}

// CloudFormationType returns the CloudFormation type for a AmazonApiGatewayV2 Stage.
func (Stage) CloudFormationType() string { return "AWS::ApiGatewayV2::Stage" }
