// Code generated by awsgen from api version 2018-11-29. DO NOT EDIT.

package apigatewayv2

import "time"

// VpcLink manages AmazonApiGatewayV2 VpcLinks.
type VpcLink struct {
	// The name of the VPC link.
	Name string `input:"name"`

	// A list of security group IDs for the VPC link.
	SecurityGroups []string `input:"security_groups" json:"SecurityGroupIds"`

	// A list of subnet IDs to include in the VPC link.
	Subnets []string `input:"subnets" json:"SubnetIds"`

	// A list of tags.
	Tags map[string]string `input:"tags"`

	// Outputs:

	// The timestamp when the VPC link was created.
	Created *time.Time `json:"CreatedDate" output:"created"`

	// The ID of the VPC link.
	ID *string `json:"VpcLinkId" output:"id"`

	// The status of the VPC link.
	Status *string `json:"VpcLinkStatus" output:"status"`

	// A message summarizing the cause of the status of the VPC link.
	StatusMessage *string `json:"VpcLinkStatusMessage" output:"status_message"`

	// The version of the VPC link.
	VPCLinkVersion *string `json:"VpcLinkVersion" output:"vpc_link_version"`
}
