// Code generated by "stringer -type Style"; DO NOT EDIT.

package ui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Bold-1]
	_ = x[Dim-2]
	_ = x[Italic-3]
	_ = x[Underline-4]
	_ = x[Invert-7]
	_ = x[Hidden-8]
	_ = x[Strikethrough-9]
	_ = x[Black-30]
	_ = x[Red-31]
	_ = x[Green-32]
	_ = x[Yellow-33]
	_ = x[Blue-34]
	_ = x[Magenta-35]
	_ = x[Cyan-36]
	_ = x[White-37]
	_ = x[HiBlack-90]
	_ = x[HiRed-91]
	_ = x[HiGreen-92]
	_ = x[HiYellow-93]
	_ = x[HiBlue-94]
	_ = x[HiMagenta-95]
	_ = x[HiCyan-96]
	_ = x[HiWhite-97]
	_ = x[BGBlack-40]
	_ = x[BGRed-41]
	_ = x[BGGreen-42]
	_ = x[BGYellow-43]
	_ = x[BGBlue-44]
	_ = x[BGMagenta-45]
	_ = x[BGCyan-46]
	_ = x[BGWhite-47]
	_ = x[BGHiBlack-100]
	_ = x[BGHiRed-101]
	_ = x[BGHiGreen-102]
	_ = x[BGHiYellow-103]
	_ = x[BGHiBlue-104]
	_ = x[BGHiMagenta-105]
	_ = x[BGHiCyan-106]
	_ = x[BGHiWhite-107]
}

const (
	_Style_name_0 = "BoldDimItalicUnderline"
	_Style_name_1 = "InvertHiddenStrikethrough"
	_Style_name_2 = "BlackRedGreenYellowBlueMagentaCyanWhite"
	_Style_name_3 = "BGBlackBGRedBGGreenBGYellowBGBlueBGMagentaBGCyanBGWhite"
	_Style_name_4 = "HiBlackHiRedHiGreenHiYellowHiBlueHiMagentaHiCyanHiWhite"
	_Style_name_5 = "BGHiBlackBGHiRedBGHiGreenBGHiYellowBGHiBlueBGHiMagentaBGHiCyanBGHiWhite"
)

var (
	_Style_index_0 = [...]uint8{0, 4, 7, 13, 22}
	_Style_index_1 = [...]uint8{0, 6, 12, 25}
	_Style_index_2 = [...]uint8{0, 5, 8, 13, 19, 23, 30, 34, 39}
	_Style_index_3 = [...]uint8{0, 7, 12, 19, 27, 33, 42, 48, 55}
	_Style_index_4 = [...]uint8{0, 7, 12, 19, 27, 33, 42, 48, 55}
	_Style_index_5 = [...]uint8{0, 9, 16, 25, 35, 43, 54, 62, 71}
)

func (i Style) String() string {
	switch {
	case 1 <= i && i <= 4:
		i -= 1
		return _Style_name_0[_Style_index_0[i]:_Style_index_0[i+1]]
	case 7 <= i && i <= 9:
		i -= 7
		return _Style_name_1[_Style_index_1[i]:_Style_index_1[i+1]]
	case 30 <= i && i <= 37:
		i -= 30
		return _Style_name_2[_Style_index_2[i]:_Style_index_2[i+1]]
	case 40 <= i && i <= 47:
		i -= 40
		return _Style_name_3[_Style_index_3[i]:_Style_index_3[i+1]]
	case 90 <= i && i <= 97:
		i -= 90
		return _Style_name_4[_Style_index_4[i]:_Style_index_4[i+1]]
	case 100 <= i && i <= 107:
		i -= 100
		return _Style_name_5[_Style_index_5[i]:_Style_index_5[i+1]]
	default:
		return "Style(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
