name: Go
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Download dependencies
      run: go mod download
    - name: Test
      run: make test-ci
    - name: Lint
      run: make lint
    - name: Build
      run: make build
